# suppress inspection "SpellCheckingInspection" for whole file
# suppress inspection "UnusedProperty" for whole file
spring.application.name=MainApplication
server.port=${port:8081}
spring.threads.virtual.enabled=true
spring.main.banner-mode=off
